#!/bin/bash -e

# First argument. Expects "version" or "nchan"
ARG1=$1
shift

# Print the version and die
if [[ "$ARG1" == "version" ]]; then
  /usr/local/bin/recyclarr --version
  exit $?
fi

# Publish messages to nchan sub
publish() {
  # Always log to syslog
  logger -t recyclarr "$1"

  # Publish to frontend if the argument is nchan
  if [[ "$ARG1" == "nchan" ]]; then
    curl -H "Content-Type: text/plain" -X POST --data "$1" \
      --unix-socket /var/run/nginx.socket \
      "http://localhost/pub/recyclarr?buffer_length=1"
  fi
}

# Create temporary file to hold output
FIFO=$(mktemp -u)
mkfifo $FIFO

# Run the program async and write output lines in that file
/usr/local/bin/recyclarr sync $1 2>&1 >$FIFO &

# Listen output and publish messages
while read LINE; do publish "$LINE"; done <$FIFO

# Wait program ends and send last message
wait
publish "[DONE]"
rm $FIFO
